define(['layout/module',
    'datatables',
    'datatables-bootstrap',
    'datatables-colvis',
    'datatables-tools',
    'datatables-responsive'
], function (module) {

    'use strict';

    return module.registerDirective('imagetableTableTools', function ($compile) {
        return {
            restrict: 'A',
            scope: {
                tableOptions: '='
            },
            link: function (scope, element, attributes) {

                var responsiveHelper = undefined;

                var breakpointDefinition = {
                    tablet: 1024,
                    phone: 480
                };

                var options={
                    // Tabletools options:
                    //   https://datatables.net/extensions/tabletools/button_options
                    // ====
                    "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 hidden-xs'T>r>" +
                        "t" +
                        "<'dt-toolbar-footer'<'col-sm-6 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
                    oLanguage:{
                        "sSearch": "<span class='input-group-addon input-sm'><i class='glyphicon glyphicon-search'></i></span> "
                    },
                    // "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>" +
                    //     "t" +
                    //     "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                    // oLanguage:{
                    //     "sSearch": "<span class='input-group-addon input-sm'><i class='glyphicon glyphicon-search'></i></span> ",
                    //     "sLengthMenu": "_MENU_"
                    // },

                    sFilterInput:  "form-control",
                    "oTableTools": {
                        "aButtons": [
                            "copy",
                            "csv",
                            "xls",
                            {
                                "sExtends": "pdf",
                                "sTitle": "SmartAdmin_PDF",
                                "sPdfMessage": "SmartAdmin PDF Export",
                                "sPdfSize": "letter"
                            },
                            {
                                "sExtends": "print",
                                "sMessage": "Generated by SmartAdmin <i>(press Esc to close)</i>"
                            }
                        ],
                        "sSwfPath": "plugin/datatables-tabletools/swf/copy_csv_xls_pdf.swf"
                    },
                    "autoWidth": false,
                    // "smartResponsiveHelper": null,
                    preDrawCallback: function () {
                        // Initialize the responsive datatables helper once.
                        if (!responsiveHelper) {
                            responsiveHelper = new ResponsiveDatatablesHelper(element, breakpointDefinition);
                        }

                        // if (!this.smartResponsiveHelper) {
                        //     this.smartResponsiveHelper = new ResponsiveDatatablesHelper(element, {
                        //         tablet: 1024,
                        //         phone: 480
                        //     });
                        // }
                    },
                    rowCallback: function (nRow) {
                        responsiveHelper.createExpandIcon(nRow);

                        // this.smartResponsiveHelper.createExpandIcon(nRow);
                    },
                    drawCallback: function (oSettings) {
                        responsiveHelper.respond();
                        
                        // this.smartResponsiveHelper.respond();
                    }
                };

                if(attributes.tableOptions){
                    options = angular.extend(options, scope.tableOptions)
                }

                var _dataTable;

                _dataTable =  element.DataTable(options);
                element.on( 'click', 'tr', function () {
                    if ( $(this).hasClass('highlight') ) {
                        $(this).removeClass('highlight');
                    }
                    else {
                        _dataTable.$('tr.highlight').removeClass('highlight');
                        $(this).addClass('highlight');
                    }
                } );





            }
        }
    });
});
